/*
 * remote version of "receive.c"
*/
#include <string.h>
#include <stdio.h>
#include <rpc/rpc.h>
#include "msg.h"  /* msg.h generated by rpcgen */

//check whether the line contains "C00L" or not
//if the line contains "C00L", return the original line
//or return NULL
char* receive(char *line, const char *code)
{
    if(strstr(line, code) != NULL)
    {
        return line;
    }
    else
    {
        return NULL;
    }
}

/*SHARED_MEMORY PROGRAM will demonstate a rpc call*/
int main(int argc, char *argv[])
{
    CLIENT *cl;
    int *result;
    char *server;
    int flag;
    
    //Only support one parameter
    if (argc != 2)
    {
        printf("Usage: clinet hostname not appropriate!");
        exit(1);
    }
    
    //create client
    cl = clnt_create(argv[1], SHARED_MEMORY_PROG, SHARED_MEMORY_VERS, "tcp");
    if (cl == NULL) {
        clnt_pcreateerror(argv[1]);
        exit(1);
    }
    
    //get server
    server = argv[1];
    
    //if the line contains the secret code "C00L".
    //sends this information as parameter to SHARED_MEMORY program
    while(1)
    {
        //get alpha numeric strings as input from the user
        //one line at a time
        char *line;
        size_t len = 0;
        sleep(2);
        
        printf("Please input your command:\n");
        if((flag = getline(&line, &len, stdin)) == -1)
        {
            clnt_destroy(cl);
            exit(0);
        }
        
        //printf("%s %d", line, len);
        if(strcmp(line, "exit\n") == 0)
        {
            clnt_destroy(cl);
            exit(0);
        }
        
        //if the line contains the secret code "C00L", call the remote procedure msg on the server
        if(receive(line, "C00L")!= NULL)
        {
            result = msg_1(&line, cl);
            
            if (result == (int *)NULL)//an error occurred while calling the remote procedure, exit
            {
                clnt_perror(cl, server);
                clnt_destroy(cl);
                exit(1);
            }
            //succesfully called remote procedure
            printf("Back from shared_memory\n");
            
            //server was unable to print our message into a file
            //result is 0
            if (*result != 1)
            {
                clnt_perror(cl,argv[1]);
                clnt_destroy(cl);
                exit(1);
            }
        }
    }
    
    clnt_destroy(cl);
    return 0;
}
